### PR TITLE
IOGT 16: Chevron Display Fix

### PR DESCRIPTION
**Pull request by Mitso**

### CODE REVIEW

**Comment by Mitso** [comment]
@peterp please review

screen shot 2016-08-22 at 12 40 59 pm

**Comment by peterp** [comment]
@Mitso is there any way that you can align the arrows in the middle?

**Comment by peterp** [comment]
@Mitso can I see a screenshot?

**Comment by Mitso** [comment]
@peterp  please review
The footer icon is not yet aligned. Updating that on a different ticket.

screen shot 2016-08-22 at 12 40 59 pm

**Comment by Mitso** [comment]
Updated:
screen shot 2016-08-22 at 1 52 55 pm

**Comment by Mitso** [comment]
@peterp please see update

**Comment by peterp** [comment]
👍

**Pull request merged**
