### PR TITLE
IOGT 9: Footer links section

### PR DESCRIPTION
**Pull request by Mitso**

### CODE REVIEW

**Comment by Mitso** [comment]
@peterp please review 

screenshot 2016-08-10 12 14 03

**Comment by peterp** [comment]
@Mitso is it possible to specify an icon in wagtail for the dynamic footer links, eg.: for "About internet of good things?"

**Comment by Mitso** [comment]
@peterp yes that is possible and currently implemented above.

**Comment by peterp** [comment]
@Mitso Can you show me what that looks like?

**Comment by Mitso** [comment]
@peterp  I just added a random image here: 
random

**Comment by peterp** [comment]
👍

**Pull request merged**
