### PR TITLE
Adding IoGT styles.

### PR DESCRIPTION
**Pull request by peterp**

### CODE REVIEW

**Comment by peterp** [comment]
screenshot 2016-05-04 11 04 38
screenshot 2016-05-04 11 04 44
screenshot 2016-05-04 11 04 50
screenshot 2016-05-04 11 04 55

**Comment by peterp** [comment]
@saeedmb8 do you want to add your `versions.scss` file in this pull-request?

**Comment by smarzban** [comment]
@peterp Done :)

**Comment by smarzban** [comment]
@peterp 👍  🍰 🍰 🍰 🍰 🍰 🍰 🍰

**Pull request merged**
