### PR TITLE
version update and template update

### PR DESCRIPTION
**Pull request by g1039**

### CODE REVIEW

**Comment by g1039** [comment]
@codiebeulaine please review cc @miltontony

**Comment by codiebeulaine** [comment]
👍 once merge conflicts have been solved and travis

**Comment by miltontony** [comment]
@TrevorOctober @codiebeulaine this was closed without being merged.

**Comment by g1039** [comment]
@miltontony i accidentally deleted **feature/issue-57-bump-new-version-and-template-update** branch locally, so i decided to replace #60 with #62

**Pull request closed without merging**
