### PR TITLE
remove reaction questions from menu and index page

### PR DESCRIPTION
**Pull request by moh-moola**

### CODE REVIEW

**Review by KaitCrawford — APPROVED** [review]
:+1: looks good to me

**Review by smarzban — CHANGES_REQUESTED** [review]
Please lets hold off on landing this until after the IoGT migration is completed

**Comment by moh-moola** [comment]
@saeedmb8 Please give the go ahead to merge when all has been addressed with the migrations

**Review by smarzban — APPROVED** [review]
🍰

**Pull request merged**
