### PR TITLE
use molo boostrap dockerfile

### PR DESCRIPTION
**Pull request by miltontony**

### CODE REVIEW

**Comment by miltontony** [comment]
@saeedmb8 review please?
Can we land this and test in QA?

**Review by JayH5 — APPROVED** [review]
:+1:

**Comment by smarzban** [comment]
@JayH5 ready for review

**Review by JayH5 — APPROVED** [review]
:+1:, if you want to do something like praekelt/molo-tuneme#466 in a separate PR.

**Review by JayH5 — APPROVED** [review]
:+1:

**Pull request merged**
