### PR TITLE
fix comment reporting when user is logged out

### PR DESCRIPTION
**Pull request by g1039**

### CODE REVIEW

**Comment by g1039** [comment]
@saeedmb8 Ready for review

**Comment by smarzban** [comment]
@TrevorOctober the `LOGIN_URL` in the [settings](https://github.com/praekelt/molo-iogt/blob/develop/iogt/settings/base.py#L401) is pointing to `wagtailadmin_login` where in fact it should be point to `molo.profiles:auth_login` and that's why when a user is not registered it will direct them to wagtail login page

**Comment by g1039** [comment]
@saeedmb8  | @miltontony Ready for re-review

**Review by miltontony — COMMENTED** [review]
Test please

**Comment by smarzban** [comment]
👍

**Pull request merged**
