### PR TITLE
Add additional fields for registration

### PR DESCRIPTION
**Pull request by g1039**

### CODE REVIEW

**Comment by g1039** [comment]
done
edit
reg
view profile

**Comment by g1039** [comment]
@Mitso Ready for review

**Comment by Mitso** [comment]
@Ntu2koTrevor 👍 just a question why are labels uppercase by default? 
Please make them normal, with the first letter capital then CSS will updates them accordingly.

**Comment by g1039** [comment]
@Mitso Please re-review

**Comment by Mitso** [comment]
:100: :cake:

**Pull request merged**
