### PR TITLE
IOGT 7: Survey success page

### PR DESCRIPTION
**Pull request by Mitso**

### CODE REVIEW

**Comment by Mitso** [comment]
@peterp please review 

screenshot 2016-08-08 11 07 29

**Comment by Mitso** [comment]
screenshot 2016-08-08 11 08 32

**Comment by peterp** [comment]
@Mitso Can you reduce the spacing on feature phones?

**Comment by Mitso** [comment]
@peterp this is update: 

screenshot 2016-08-08 11 37 40

**Comment by peterp** [comment]
Thanks, the ticket also mentioned something about wrapping text? Was that fixed?

**Comment by Mitso** [comment]
@peterp that is now update:

screenshot 2016-08-08 12 06 25

**Comment by peterp** [comment]
👍

**Pull request merged**
