### PR TITLE
IOGT 17: Article remove date

### PR DESCRIPTION
**Pull request by Mitso**

### CODE REVIEW

**Comment by Mitso** [comment]
@peterp please review 

Showing date
screenshot 2016-08-22 16 21 11

Updated
screenshot 2016-08-22 16 19 59

**Comment by peterp** [comment]
@Mitso is the date displayed anywhere else? Do we still use `f-small` and those kind of things in this site?

**Comment by Mitso** [comment]
@peterp it is only displayed on the section and subsection page below each article. 
We do not use f-small class anymore but font-variables.

**Comment by peterp** [comment]
👍

**Pull request merged**
